services:
  authservice-api:
    build:
      context: .
      dockerfile: AuthService.Api/Dockerfile
    depends_on:
      - postgres-auth
      - authservice-migrator
    ports:
      - "${AUTHSERVICE_PORT}:${AUTHSERVICE_INTERNAL_PORT}"
    environment:
      - ConnectionStrings__DefaultConnection=${AUTHSERVICE_CONNECTION_STRING}
    volumes:
      - db_auth_data:/var/lib/postgresql/data
    env_file:
      - .env
      
  postgres-auth:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_AUTHSERVICE_USER}
      POSTGRES_PASSWORD: ${POSTGRES_AUTHSERVICE_PASSWORD}
      POSTGRES_DB: ${POSTGRES_AUTHSERVICE_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5430:5433"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    
  authservice-migrator:
    build:
      context: .
      dockerfile: AuthService.Migrator/Dockerfile
    depends_on:
      - postgres-auth
    environment:
      - ConnectionStrings__DefaultConnection=${AUTHSERVICE_CONNECTION_STRING}
    restart: no
    env_file:
      - .env
      
    
volumes:
  db_auth_data:

